# JDBC Configuration for Database Connection (AWS RDS)
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=mysql -h newdatabase.cu78wgw0swvv.us-east-1.rds.amazonaws.com -P 3306
jdbc.username=admin
jdbc.password=admin123


# Memcached Configuration For Active and StandBy Host (AWS ElastiCache)
# For Active Host
memcached.active.host=memcache.6rccng.cfg.use1.cache.amazonaws.com
memcached.active.port=11211

# For StandBy Host (optional – keep same or remove if single endpoint)
memcached.standBy.host=elasticache.6rccng.cfg.use1.cache.amazonaws.com
memcached.standBy.port=11211


# RabbitMQ Configuration (AWS MQ)
rabbitmq.address=b-aa809b61-93c8-4d8c-ae82-e20f1d7c0ecc.mq.us-east-1.on.aws
rabbitmq.port=5671
rabbitmq.username=admin
rabbitmq.password=Rajesh@test123


# Elasticsearch Configuration
elasticsearch.host=192.168.1.85
elasticsearch.port=9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
