# JDBC Configuration for Database Connection (AWS RDS)
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://database-1.cu78wgw0swvv.us-east-1.rds.amazonaws.com:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
jdbc.username=admin
jdbc.password=admin123


# Memcached Configuration For Active and StandBy Host (AWS ElastiCache)
# For Active Host
memcached.active.host=elasticache.6rccng.cfg.use1.cache.amazonaws.com
memcached.active.port=11211

# For StandBy Host (optional – keep same or remove if single endpoint)
memcached.standBy.host=elasticache.6rccng.cfg.use1.cache.amazonaws.com
memcached.standBy.port=11211


# RabbitMQ Configuration (AWS MQ)
rabbitmq.address=b-46c10ebc-6021-4e24-8df7-93d48688b84f.mq.us-east-1.on.aws
rabbitmq.port=5671
rabbitmq.username=admin123
rabbitmq.password=adminrajesh@123


# Elasticsearch Configuration
elasticsearch.host=192.168.1.85
elasticsearch.port=9300
elasticsearch.cluster=vprofile
elasticsearch.node=vprofilenode
